[package]
name = "marius-fragment-forge"
description = "Build-time HTML render generator for the Marius engine. Computes static/dynamic buffer capacities."
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
authors.workspace = true
keywords = ["codegen", "build-script", "marius"]
categories = ["development-tools"]

# regex : non pas pour nous économiser quelques lignes de code,
# mais afin de permettre exactement la même définition lexicale côté SQL et côté Forge,
# exprimée de manière lisible et testable.
[dependencies]
regex = { workspace = true }
