
[package]
name = "marius"
description = "Marius: a data-oriented reactive projection engine. PostgreSQL → AOT HTML, zero intermediate transformation."
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
authors.workspace = true
keywords = ["ecs", "dod", "reactive", "cms", "aot"]
categories = ["web-programming", "database", "concurrency"]

[dependencies]
marius-collector = { version = "=0.5.0", path = "../core/collector" }
marius-projection = { version = "=0.5.0", path = "../core/projection" }
marius-render = { version = "=0.5.0", path = "../shell/render" }
